export const ADD_REGISTER = "ADD_REGISTER";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const GET_CITY = "GET_CITY";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_SELECTED_PRODUCT = "GET_SELECTED_PRODUCT";
export const GET_PRODUCT_SELLER = "GET_PRODUCT_SELLER";
export const BUY_PRODUCT = "BUY_PRODUCT";

export const GET_ALL_NOTIF_SELLER = "GET_ALL_NOTIF_SELLER";
export const GET_ALL_NOTIF_BUYER = "GET_ALL_NOTIF_BUYER";

export const GET_TRANSACTION_DETAIL = "GET_TRANSACTION_DETAIL";
export const ACCEPT_TRANSACTION = "ACCEPT_TRANSACTION";
export const CANCEL_TRANSACTION = "CANCEL_TRANSACTION";
export const SUCCESS_TRANSACTION = "SUCCESS_TRANSACTION";

export const GET_ALL_DAFTARJUAL = "GET_ALL_DAFTARJUAL";
export const GET_ALL_WISHLIST = "GET_ALL_WISHLIST";
export const GET_ALL_TERJUAL = "GET_ALL_TERJUAL";
