export const ADD_REGISTER = "ADD_REGISTER";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_SELECTED_PRODUCT = "GET_SELECTED_PRODUCT";
export const GET_PRODUCT_SELLER = "GET_PRODUCT_SELLER";

export const GET_ALL_DAFTARJUAL = "GET_ALL_DAFTARJUAL";